name: SSH to EC2 and docker compose

on: push

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build the docker_compose
      run: docker compose up -d --build
    
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}  #get it from iris.pem
            HOSTNAME : ${{ secrets.HOSTNAME  }}           #your AWS IPv4 address
            USER_NAME : ${{ secrets.USER_NAME  }}         #"ubuntu"
        run: |
          pwd
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME}
            cd /home/ubuntu/Deploy-ML-Production &&
            git checkout main &&
            git pull &&
            sudo docker compose up -d
